In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,Match Report,NaN,15.0,7.0,19.1,0.0,0,0,2024,Arsenal
2,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,Match Report,NaN,13.0,2.0,16.4,0.0,1,1,2024,Arsenal
3,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,Match Report,NaN,18.0,9.0,13.8,0.0,1,1,2024,Arsenal
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,Match Report,NaN,17.0,5.0,15.0,0.0,0,0,2024,Arsenal
5,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,Match Report,NaN,13.0,4.0,17.4,0.0,0,0,2024,Arsenal

In [4]:
matches.shape

(714, 27)

In [5]:
matches["team"].value_counts()

Arsenal                     36
Wolverhampton Wanderers     36
Burnley                     36
Luton Town                  36
Nottingham Forest           36
Brentford                   36
Everton                     36
Crystal Palace              36
Fulham                      36
Sheffield United            36
Bournemouth                 36
West Ham United             36
Aston Villa                 36
Liverpool                   36
Manchester City             35
Manchester United           35
Chelsea                     35
Newcastle United            35
Tottenham Hotspur           35
Brighton and Hove Albion    35
Name: team, dtype: int64

In [6]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,Match Report,NaN,13.0,1.0,17.8,0.0,0,0,2024,Liverpool
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,Match Report,NaN,25.0,9.0,16.8,1.0,0,1,2024,Liverpool
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,9.0,4.0,17.2,1.0,0,0,2024,Liverpool
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,Match Report,NaN,17.0,4.0,14.7,0.0,0,0,2024,Liverpool
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,Match Report,NaN,16.0,5.0,15.8,0.0,0,0,2024,Liverpool
6,2023-09-24,14:00,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,West Ham,...,Match Report,NaN,21.0,6.0,19.3,2.0,1,1,2024,Liverpool
8,2023-09-30,17:30,Premier League,Matchweek 7,Sat,Away,L,1.0,2.0,Tottenham,...,Match Report,NaN,12.0,4.0,14.9,0.0,0,0,2024,Liverpool
10,2023-10-08,14:00,Premier League,Matchweek 8,Sun,Away,D,2.0,2.0,Brighton,...,Match Report,NaN,13.0,3.0,18.8,0.0,1,1,2024,Liverpool
11,2023-10-21,12:30,Premier League,Matchweek 9,Sat,Home,W,2.0,0.0,Everton,...,Match Report,NaN,25.0,5.0,22.4,1.0,1,1,2024,Liverpool
13,2023-10-29,14:00,Premier League,Matchweek 10,Sun,Home,W,3.0,0.0,Nott'ham Forest,...,Match Report,NaN,21.0,8.0,19.5,2.0,0,0,2024,Liverpool
15,2023-11-05,16:30,Premier League,Matchweek 11,Sun,Away,D,1.0,1.0,Luton Town,...,Match Report,NaN,24.0,6.0,17.5,0.0,0,0,2024,Liverpool
17,2023-11-12,14:00,Premier League,Matchweek 12,Sun,Home,W,3.0,0.0,Brentford,...,Match Report,NaN,17.0,10.0,19.0,0.0,0,0,2024,Liverpool
18,2023-11-25,12:30,Premier League,Matchweek 13,Sat,Away,D,1.0,1.0,Manchester City,...,Match Report,NaN,8.0,3.0,15.9,0.0,0,0,2024,Liverpool
20,2023-12-03,14:00,Premier League,Matchweek 14,Sun,Home,W,4.0,3.0,Fulham,...,Match Report,NaN,26.0,12.0,18.9,1.0,0,0,2024,Liverpool
21,2023-12-06,19:30,Premier League,Matchweek 15,Wed,Away,W,2.0,0.0,Sheffield Utd,...,Match Report,NaN,15.0,8.0,16.4,0.0,0,0,2024,Liverpool
22,2023-12-09,12:30,Premier League,Matchweek 16,Sat,Away,W,2.0,1.0,Crystal Palace,...,Match Report,NaN,14.0,2.0,17.4,0.0,0,0,2024,Liverpool
24,2023-12-17,16:30,Premier League,Matchweek 17,Sun,Home,D,0.0,0.0,Manchester Utd,...,Match Report,NaN,34.0,8.0,17.7,0.0,0,0,2024,Liverpool
26,2023-12-23,17:30,Premier League,Matchweek 18,Sat,Home,D,1.0,1.0,Arsenal,...,Match Report,NaN,13.0,3.0,20.1,1.0,0,0,2024,Liverpool
27,2023-12-26,17:30,Premier League,Matchweek 19,Tue,Away,W,2.0,0.0,Burnley,...,Match Report,NaN,19.0,10.0,17.4,0.0,0,0,2024,Liverpool
28,2024-01-01,20:00,Premier League,Matchweek 20,Mon,Home,W,4.0,2.0,Newcastle Utd,...,Match Report,NaN,32.0,12.0,16.2,0.0,1,2,2024,Liverpool
31,2024-01-21,16:30,Premier League,Matchweek 21,Sun,Away,W,4.0,0.0,Bournemouth,...,Match Report,NaN,14.0,7.0,19.2,0.0,0,0,2024,Liverpool
34,2024-01-31,20:15,Premier League,Matchweek 22,Wed,Home,W,4.0,1.0,Chelsea,...,Match Report,NaN,27.0,13.0,19.9,2.0,0,1,2024,Liverpool
35,2024-02-04,16:30,Premier League,Matchweek 23,Sun,Away,L,1.0,3.0,Arsenal,...,Match Report,NaN,10.0,1.0,19.7,0.0,0,0,2024,Liverpool
36,2024-02-10,15:00,Premier League,Matchweek 24,Sat,Home,W,3.0,1.0,Burnley,...,Match Report,NaN,25.0,10.0,15.4,0.0,0,0,2024,Liverpool
37,2024-02-17,12:30,Premier League,Matchweek 25,Sat,Away,W,4.0,1.0,Brentford,...,Match Report,NaN,15.0,8.0,15.9,1.0,0,0,2024,Liverpool
38,2024-02-21,19:30,Premier League,Matchweek 26,Wed,Home,W,4.0,1.0,Luton Town,...,Match Report,NaN,29.0,13.0,16.9,0.0,0,0,2024,Liverpool
41,2024-03-02,15:00,Premier League,Matchweek 27,Sat,Away,W,1.0,0.0,Nott'ham Forest,...,Match Report,NaN,22.0,1.0,14.6,0.0,0,0,2024,Liverpool
43,2024-03-10,15:45,Premier League,Matchweek 28,Sun,Home,D,1.0,1.0,Manchester City,...,Match Report,NaN,18.0,5.0,19.0,1.0,1,1,2024,Liverpool
46,2024-03-31,14:00,Premier League,Matchweek 30,Sun,Home,W,2.0,1.0,Brighton,...,Match Report,NaN,30.0,8.0,16.6,0.0,0,0,2024,Liverpool
47,2024-04-04,19:30,Premier League,Matchweek 31,Thu,Home,W,3.0,1.0,Sheffield Utd,...,Match Report,NaN,29.0,9.0,18.1,1.0,0,0,2024,Liverpool
48,2024-04-07,15:30,Premier League,Matchweek 32,Sun,Away,D,2.0,2.0,Manchester Utd,...,Match Report,NaN,27.0,6.0,17.5,0.0,1,1,2024,Liverpool
50,2024-04-14,14:00,Premier League,Matchweek 33,Sun,Home,L,0.0,1.0,Crystal Palace,...,Match Report,NaN,21.0,5.0,12.5,1.0,0,0,2024,Liverpool
52,2024-04-21,16:30,Premier League,Matchweek 34,Sun,Away,W,3.0,1.0,Fulham,...,Match Report,NaN,14.0,7.0,18.8,2.0,0,0,2024,Liverpool
53,2024-04-24,20:00,Premier League,Matchweek 29,Wed,Away,L,0.0,2.0,Everton,...,Match Report,NaN,23.0,7.0,16.8,0.0,0,0,2024,Liverpool
54,2024-04-27,12:30,Premier League,Matchweek 35,Sat,Away,D,2.0,2.0,West Ham,...,Match Report,NaN,28.0,8.0,16.6,1.0,0,0,2024,Liverpool
55,2024-05-05,16:30,Premier League,Matchweek 36,Sun,Home,W,4.0,2.0,Tottenham,...,Match Report,NaN,25.0,12.0,15.3,0.0,0,0,2024,Liverpool

In [7]:
matches["round"].value_counts()

Matchweek 1     20
Matchweek 27    20
Matchweek 21    20
Matchweek 22    20
Matchweek 23    20
Matchweek 24    20
Matchweek 25    20
Matchweek 26    20
Matchweek 28    20
Matchweek 2     20
Matchweek 30    20
Matchweek 31    20
Matchweek 32    20
Matchweek 33    20
Matchweek 29    20
Matchweek 35    20
Matchweek 20    20
Matchweek 19    20
Matchweek 18    20
Matchweek 17    20
Matchweek 3     20
Matchweek 4     20
Matchweek 5     20
Matchweek 6     20
Matchweek 7     20
Matchweek 8     20
Matchweek 9     20
Matchweek 10    20
Matchweek 11    20
Matchweek 12    20
Matchweek 13    20
Matchweek 14    20
Matchweek 15    20
Matchweek 16    20
Matchweek 36    20
Matchweek 34    14
Name: round, dtype: int64

In [8]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [9]:
matches = matches.drop(columns=['comp', 'notes', 'season'])

In [10]:
matches["date"] = pd.to_datetime(matches["date"])

In [11]:
matches["target"] = (matches["result"] == "W").astype("int")

In [12]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,referee,match report,sh,sot,dist,fk,pk,pkatt,team,target
1,2023-08-12,12:30,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,0.8,...,Michael Oliver,Match Report,15.0,7.0,19.1,0.0,0,0,Arsenal,1
2,2023-08-21,20:00,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,2.0,...,David Coote,Match Report,13.0,2.0,16.4,0.0,1,1,Arsenal,1
3,2023-08-26,15:00,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,3.2,...,Paul Tierney,Match Report,18.0,9.0,13.8,0.0,1,1,Arsenal,0
4,2023-09-03,16:30,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,2.3,...,Anthony Taylor,Match Report,17.0,5.0,15.0,0.0,0,0,Arsenal,1
5,2023-09-17,16:30,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,1.0,...,Simon Hooper,Match Report,13.0,4.0,17.4,0.0,0,0,Arsenal,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,2024-04-13,15:00,Matchweek 33,Sat,Away,L,0.0,2.0,Brentford,0.8,...,Samuel Barrott,Match Report,8.0,2.0,15.1,0.0,0,0,Sheffield United,0
35,2024-04-20,15:00,Matchweek 34,Sat,Home,L,1.0,4.0,Burnley,2.4,...,Andy Madley,Match Report,18.0,11.0,14.9,0.0,0,0,Sheffield United,0
36,2024-04-24,20:00,Matchweek 29,Wed,Away,L,2.0,4.0,Manchester Utd,0.8,...,Michael Salisbury,Match Report,10.0,4.0,17.8,1.0,0,0,Sheffield United,0
37,2024-04-27,15:00,Matchweek 35,Sat,Away,L,1.0,5.0,Newcastle Utd,1.5,...,Tony Harrington,Match Report,15.0,4.0,13.5,0.0,0,0,Sheffield United,0
38,2024-05-04,15:00,Matchweek 36,Sat,Home,L,1.0,3.0,Nott'ham Forest,2.2,...,Chris Kavanagh,Match Report,16.0,4.0,18.0,0.0,1,1,Sheffield United,0

In [13]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [14]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [15]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [16]:
matches["day_code"] = matches["date"].dt.dayofweek

In [17]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,dist,fk,pk,pkatt,team,target,venue_code,opp_code,hour,day_code
1,2023-08-12,12:30,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,0.8,...,19.1,0.0,0,0,Arsenal,1,1,15,12,5
2,2023-08-21,20:00,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,2.0,...,16.4,0.0,1,1,Arsenal,1,0,7,20,0
3,2023-08-26,15:00,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,3.2,...,13.8,0.0,1,1,Arsenal,0,1,9,15,5
4,2023-09-03,16:30,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,2.3,...,15.0,0.0,0,0,Arsenal,1,1,13,16,6
5,2023-09-17,16:30,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,1.0,...,17.4,0.0,0,0,Arsenal,1,0,8,16,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,2024-04-13,15:00,Matchweek 33,Sat,Away,L,0.0,2.0,Brentford,0.8,...,15.1,0.0,0,0,Sheffield United,0,0,3,15,5
35,2024-04-20,15:00,Matchweek 34,Sat,Home,L,1.0,4.0,Burnley,2.4,...,14.9,0.0,0,0,Sheffield United,0,1,5,15,5
36,2024-04-24,20:00,Matchweek 29,Wed,Away,L,2.0,4.0,Manchester Utd,0.8,...,17.8,1.0,0,0,Sheffield United,0,0,13,20,2
37,2024-04-27,15:00,Matchweek 35,Sat,Away,L,1.0,5.0,Newcastle Utd,1.5,...,13.5,0.0,0,0,Sheffield United,0,0,14,15,5
38,2024-05-04,15:00,Matchweek 36,Sat,Home,L,1.0,3.0,Nott'ham Forest,2.2,...,18.0,0.0,1,1,Sheffield United,0,1,15,15,5

In [18]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
rf = RandomForestClassifier(n_estimators=100, min_samples_split=20, random_state=1)

In [20]:
train = matches[matches["date"] < '2024-01-01']
train.describe()

,gf,ga,xg,xga,poss,attendance,sh,sot,dist,fk,pk,pkatt,target,venue_code,opp_code,hour,day_code
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,1.556122,1.556122,1.506122,1.506122,50.000000,38291.897959,13.165816,4.418367,16.740306,0.359694,0.130102,0.142857,0.408163,0.500000,9.505102,15.688776,4.704082
std,1.276149,1.276149,0.838226,0.838226,13.819627,17727.024935,5.622894,2.519178,3.022492,0.559236,0.358901,0.371628,0.492122,0.500639,5.781616,2.225193,1.511823
min,0.000000,0.000000,0.000000,0.000000,20.000000,10290.000000,2.000000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000
25%,1.000000,1.000000,0.900000,0.900000,39.000000,24444.750000,9.000000,3.000000,14.900000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,14.000000,5.000000
50%,1.000000,1.000000,1.300000,1.300000,50.000000,31812.000000,12.000000,4.000000,16.700000,0.000000,0.000000,0.000000,0.000000,0.500000,9.000000,15.000000,5.000000
75%,2.000000,2.000000,2.100000,2.100000,61.000000,53117.250000,16.000000,6.000000,18.325000,1.000000,0.000000,0.000000,1.000000,1.000000,15.000000,17.000000,6.000000
max,8.000000,8.000000,4.100000,4.100000,80.000000,73607.000000,34.000000,15.000000,39.900000,2.000000,2.000000,2.000000,1.000000,1.000000,19.000000,20.000000,6.000000

In [21]:
test = matches[matches["date"] > '2024-01-01']
test.describe()

,gf,ga,xg,xga,poss,attendance,sh,sot,dist,fk,pk,pkatt,target,venue_code,opp_code,hour,day_code
count,320.00000,320.00000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.00000,320.000000
mean,1.71875,1.71875,1.568437,1.568437,50.000000,38533.543750,14.156250,4.893750,16.753750,0.384375,0.128125,0.143750,0.362500,0.500000,9.450000,16.20625,4.318750
std,1.40162,1.40162,0.892377,0.892377,13.884205,18081.797256,6.335992,2.716712,2.640625,0.627784,0.370321,0.385422,0.481475,0.500783,5.794603,2.41494,1.824157
min,0.00000,0.00000,0.100000,0.100000,18.000000,10994.000000,2.000000,0.000000,8.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.00000,0.000000
25%,1.00000,1.00000,0.900000,0.900000,40.000000,24417.000000,9.000000,3.000000,14.900000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,15.00000,3.750000
50%,1.00000,1.00000,1.400000,1.400000,50.000000,38193.000000,13.000000,5.000000,16.750000,0.000000,0.000000,0.000000,0.000000,0.500000,9.000000,15.00000,5.000000
75%,3.00000,3.00000,2.100000,2.100000,60.000000,53445.000000,18.000000,6.000000,18.500000,1.000000,0.000000,0.000000,1.000000,1.000000,14.250000,19.00000,5.000000
max,6.00000,6.00000,4.200000,4.200000,82.000000,73612.000000,36.000000,15.000000,25.400000,3.000000,2.000000,2.000000,1.000000,1.000000,19.000000,20.00000,6.000000

In [22]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [23]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=20, random_state=1)

In [24]:
preds = rf.predict(test[predictors])

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
error = accuracy_score(test["target"], preds)

In [27]:
error

0.609375

In [28]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [29]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          157  47
1           78  38

In [66]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.4470588235294118

In [31]:
grouped_matches = matches.groupby("team")

In [32]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [33]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [34]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2023-09-02,15:00,Matchweek 4,Sat,Home,W,5.0,1.0,Fulham,2.2,...,15,5,2.000000,0.333333,20.000000,7.000000,16.366667,0.666667,0.000000,0.333333
6,2023-09-16,15:00,Matchweek 5,Sat,Away,W,3.0,1.0,West Ham,3.6,...,15,5,2.666667,0.666667,16.333333,5.666667,16.666667,0.666667,0.333333,0.666667
8,2023-09-23,15:00,Matchweek 6,Sat,Home,W,2.0,0.0,Nott'ham Forest,1.3,...,15,5,3.333333,1.000000,21.333333,8.666667,16.166667,1.000000,0.333333,0.666667
10,2023-09-30,15:00,Matchweek 7,Sat,Away,L,1.0,2.0,Wolves,0.9,...,15,5,3.333333,0.666667,14.000000,7.000000,16.133333,1.000000,0.333333,0.333333
12,2023-10-08,16:30,Matchweek 8,Sun,Away,L,0.0,1.0,Arsenal,0.5,...,16,6,2.000000,1.000000,19.666667,8.333333,17.633333,1.333333,0.000000,0.000000
13,2023-10-21,15:00,Matchweek 9,Sat,Home,W,2.0,1.0,Brighton,0.8,...,15,5,1.000000,1.000000,11.333333,4.000000,17.133333,1.000000,0.000000,0.000000
15,2023-10-29,15:30,Matchweek 10,Sun,Away,W,3.0,0.0,Manchester Utd,4.0,...,15,6,1.000000,1.333333,12.333333,4.333333,17.666667,0.666667,0.000000,0.000000
16,2023-11-04,15:00,Matchweek 11,Sat,Home,W,6.0,1.0,Bournemouth,1.9,...,15,5,1.666667,0.666667,11.333333,4.666667,16.966667,1.000000,0.333333,0.333333
18,2023-11-12,16:30,Matchweek 12,Sun,Away,D,4.0,4.0,Chelsea,2.9,...,16,6,3.666667,0.666667,17.000000,7.333333,17.466667,1.000000,0.333333,0.333333
19,2023-11-25,12:30,Matchweek 13,Sat,Home,D,1.0,1.0,Liverpool,1.3,...,12,5,4.333333,1.666667,18.333333,8.666667,16.733333,1.000000,0.666667,0.666667
21,2023-12-03,16:30,Matchweek 14,Sun,Home,D,3.0,3.0,Tottenham,2.6,...,16,6,3.666667,2.000000,17.000000,7.333333,16.433333,0.666667,0.333333,0.333333
22,2023-12-06,20:15,Matchweek 15,Wed,Away,L,0.0,1.0,Aston Villa,0.6,...,20,2,2.666667,2.666667,15.666667,6.000000,15.433333,0.666667,0.333333,0.333333
23,2023-12-10,14:00,Matchweek 16,Sun,Away,W,2.0,1.0,Luton Town,1.6,...,14,6,1.333333,1.666667,11.666667,3.666667,12.366667,0.333333,0.000000,0.000000
25,2023-12-16,15:00,Matchweek 17,Sat,Home,D,2.0,2.0,Crystal Palace,1.6,...,15,5,1.666667,1.666667,12.333333,4.000000,13.166667,0.333333,0.000000,0.000000
26,2023-12-27,20:15,Matchweek 19,Wed,Away,W,3.0,1.0,Everton,2.4,...,20,2,1.333333,1.333333,13.000000,5.666667,14.766667,0.333333,0.000000,0.000000
27,2023-12-30,15:00,Matchweek 20,Sat,Home,W,2.0,0.0,Sheffield Utd,2.2,...,15,5,2.333333,1.333333,19.666667,7.666667,18.800000,0.666667,0.333333,0.333333
29,2024-01-13,17:30,Matchweek 21,Sat,Away,W,3.0,2.0,Newcastle Utd,3.0,...,17,5,2.333333,1.000000,19.666667,7.000000,18.366667,0.333333,0.333333,0.333333
31,2024-01-31,19:30,Matchweek 22,Wed,Home,W,3.0,1.0,Burnley,1.7,...,19,2,2.666667,1.000000,22.333333,7.666667,18.733333,1.000000,0.333333,0.333333
32,2024-02-05,20:00,Matchweek 23,Mon,Away,W,3.0,1.0,Brentford,2.1,...,20,0,2.666667,1.000000,19.666667,6.333333,17.500000,1.000000,0.000000,0.000000
33,2024-02-10,12:30,Matchweek 24,Sat,Home,W,2.0,0.0,Everton,1.6,...,12,5,3.000000,1.333333,22.000000,10.000000,18.100000,1.000000,0.000000,0.000000
35,2024-02-17,17:30,Matchweek 25,Sat,Home,D,1.0,1.0,Chelsea,2.6,...,17,5,2.666667,0.666667,19.333333,7.333333,17.466667,0.333333,0.000000,0.000000
36,2024-02-20,19:30,Matchweek 18,Tue,Home,W,1.0,0.0,Brentford,2.3,...,19,1,2.000000,0.666667,25.000000,7.666667,17.500000,0.333333,0.000000,0.000000
37,2024-02-24,17:30,Matchweek 26,Sat,Away,W,1.0,0.0,Bournemouth,1.6,...,17,5,1.333333,0.333333,25.000000,6.000000,16.966667,0.333333,0.000000,0.000000
39,2024-03-03,15:30,Matchweek 27,Sun,Home,W,3.0,1.0,Manchester Utd,3.3,...,15,6,1.000000,0.333333,23.666667,7.000000,16.333333,0.666667,0.000000,0.000000
41,2024-03-10,15:45,Matchweek 28,Sun,Away,D,1.0,1.0,Liverpool,1.6,...,15,6,1.666667,0.333333,22.333333,8.000000,16.933333,0.666667,0.000000,0.000000
43,2024-03-31,16:30,Matchweek 30,Sun,Home,D,0.0,0.0,Arsenal,1.0,...,16,6,1.666667,0.666667,17.333333,6.666667,17.266667,0.666667,0.000000,0.000000
44,2024-04-03,20:15,Matchweek 31,Wed,Home,W,4.0,1.0,Aston Villa,3.4,...,20,2,1.333333,0.666667,16.333333,5.000000,16.833333,0.333333,0.000000,0.000000
45,2024-04-06,12:30,Matchweek 32,Sat,Away,W,4.0,2.0,Crystal Palace,1.9,...,12,5,1.666667,0.666667,15.666667,6.000000,16.233333,0.666667,0.000000,0.000000
47,2024-04-13,15:00,Matchweek 33,Sat,Home,W,5.0,1.0,Luton Town,4.2,...,15,5,2.666667,1.000000,18.333333,6.666667,15.400000,0.666667,0.000000,0.000000
50,2024-04-25,20:00,Matchweek 29,Thu,Away,W,4.0,0.0,Brighton,1.4,...,20,3,4.333333,1.333333,26.333333,10.333333,16.300000,0.666667,0.333333,0.333333
51,2024-04-28,16:30,Matchweek 35,Sun,Away,W,2.0,0.0,Nott'ham Forest,0.9,...,16,6,4.333333,1.000000,22.666667,8.666667,16.666667,0.333333,0.333333,0.333333
52,2024-05-04,17:30,Matchweek 36,Sat,Home,W,5.0,1.0,Wolves,3.7,...,17,5,3.666667,0.333333,20.333333,7.666667,17.533333,0.666667,0.333333,0.333333

In [35]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [36]:
matches_rolling

                                 date   time         round  day venue result  \
team
Arsenal                 4  2023-09-03  16:30   Matchweek 4  Sun  Home      W
                        5  2023-09-17  16:30   Matchweek 5  Sun  Away      W
                        7  2023-09-24  14:00   Matchweek 6  Sun  Home      D
                        9  2023-09-30  15:00   Matchweek 7  Sat  Away      W
                        11 2023-10-08  16:30   Matchweek 8  Sun  Home      W
...                               ...    ...           ...  ...   ...    ...
Wolverhampton Wanderers 38 2024-04-13  15:00  Matchweek 33  Sat  Away      D
                        39 2024-04-20  19:30  Matchweek 34  Sat  Home      L
                        40 2024-04-24  19:45  Matchweek 29  Wed  Home      L
                        41 2024-04-27  15:00  Matchweek 35  Sat  Home      W
                        42 2024-05-04  17:30  Matchweek 36  Sat  Away      L

                             gf   ga         opponent   xg  ...  hour  \
team                                                        ...
Arsenal                 4   3.0  1.0   Manchester Utd  2.3  ...    16
                        5   1.0  0.0          Everton  1.0  ...    16
                        7   2.0  2.0        Tottenham  1.8  ...    14
                        9   4.0  0.0      Bournemouth  3.4  ...    15
                        11  1.0  0.0  Manchester City  0.4  ...    16
...                         ...  ...              ...  ...  ...   ...
Wolverhampton Wanderers 38  2.0  2.0  Nott'ham Forest  1.0  ...    15
                        39  0.0  2.0          Arsenal  0.2  ...    19
                        40  0.0  1.0      Bournemouth  0.5  ...    19
                        41  2.0  1.0       Luton Town  1.2  ...    15
                        42  1.0  5.0  Manchester City  0.3  ...    17

                            day_code  gf_rolling ga_rolling sh_rolling  \
team
Arsenal                 4          6    1.666667   1.000000  15.333333
                        5          6    2.000000   1.000000  16.000000
                        7          6    2.000000   1.000000  16.000000
                        9          5    2.000000   1.000000  14.000000
                        11         6    2.333333   0.666667  12.666667
...                              ...         ...        ...        ...
Wolverhampton Wanderers 38         5    0.666667   1.666667  11.333333
                        39         5    1.333333   1.666667  10.666667
                        40         2    1.000000   2.000000   9.666667
                        41         5    0.666667   1.666667  10.333333
                        42         5    0.666667   1.333333  11.000000

                           sot_rolling dist_rolling  fk_rolling  pk_rolling  \
team
Arsenal                 4     6.000000    16.433333    0.000000    0.666667
                        5     5.333333    15.066667    0.000000    0.666667
                        7     6.000000    15.400000    0.000000    0.333333
                        9     4.333333    16.433333    0.000000    0.333333
                        11    4.666667    16.600000    0.000000    1.000000
...                                ...          ...         ...         ...
Wolverhampton Wanderers 38    3.666667    17.466667    0.666667    0.333333
                        39    3.666667    17.966667    0.333333    0.333333
                        40    4.000000    20.533333    0.333333    0.333333
                        41    3.333333    18.766667    0.000000    0.000000
                        42    4.000000    19.666667    0.000000    0.000000

                            pkatt_rolling
team
Arsenal                 4        0.666667
                        5        0.666667
                        7        0.333333
                        9        0.333333
                        11       1.000000
...                                   ...
Wolverhampton Wanderers 38       0.333333
                        39       0.333333
                        40       0.333333
                        41       0.000000
                        42       0.000000

[654 rows x 37 columns]

In [37]:
matches_rolling = matches_rolling.droplevel('team')

In [38]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2023-09-03,16:30,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,2.3,...,16,6,1.666667,1.000000,15.333333,6.000000,16.433333,0.000000,0.666667,0.666667
5,2023-09-17,16:30,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,1.0,...,16,6,2.000000,1.000000,16.000000,5.333333,15.066667,0.000000,0.666667,0.666667
7,2023-09-24,14:00,Matchweek 6,Sun,Home,D,2.0,2.0,Tottenham,1.8,...,14,6,2.000000,1.000000,16.000000,6.000000,15.400000,0.000000,0.333333,0.333333
9,2023-09-30,15:00,Matchweek 7,Sat,Away,W,4.0,0.0,Bournemouth,3.4,...,15,5,2.000000,1.000000,14.000000,4.333333,16.433333,0.000000,0.333333,0.333333
11,2023-10-08,16:30,Matchweek 8,Sun,Home,W,1.0,0.0,Manchester City,0.4,...,16,6,2.333333,0.666667,12.666667,4.666667,16.600000,0.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2024-04-13,15:00,Matchweek 33,Sat,Away,D,2.0,2.0,Nott'ham Forest,1.0,...,15,5,0.666667,1.666667,11.333333,3.666667,17.466667,0.666667,0.333333,0.333333
39,2024-04-20,19:30,Matchweek 34,Sat,Home,L,0.0,2.0,Arsenal,0.2,...,19,5,1.333333,1.666667,10.666667,3.666667,17.966667,0.333333,0.333333,0.333333
40,2024-04-24,19:45,Matchweek 29,Wed,Home,L,0.0,1.0,Bournemouth,0.5,...,19,2,1.000000,2.000000,9.666667,4.000000,20.533333,0.333333,0.333333,0.333333
41,2024-04-27,15:00,Matchweek 35,Sat,Home,W,2.0,1.0,Luton Town,1.2,...,15,5,0.666667,1.666667,10.333333,3.333333,18.766667,0.000000,0.000000,0.000000
42,2024-05-04,17:30,Matchweek 36,Sat,Away,L,1.0,5.0,Manchester City,0.3,...,17,5,0.666667,1.333333,11.000000,4.000000,19.666667,0.000000,0.000000,0.000000

In [39]:
matches_rolling.index = range(matches_rolling.shape[0])

In [42]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2024-01-01']
    test = data[data["date"] > '2024-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    model_score = rf.score(test[predictors], test["target"])
    return combined, error, model_score

In [43]:
combined, error, model_score = make_predictions(matches_rolling, predictors + new_cols)

In [44]:
error

0.574468085106383

In [45]:
model_score

0.68125

In [46]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [47]:
combined

,actual,predicted,date,team,opponent,result
17,1,1,2024-01-20,Arsenal,Crystal Palace,W
18,1,1,2024-01-30,Arsenal,Nott'ham Forest,W
19,1,1,2024-02-04,Arsenal,Liverpool,W
20,1,0,2024-02-11,Arsenal,West Ham,W
21,1,0,2024-02-17,Arsenal,Burnley,W
...,...,...,...,...,...,...
649,0,0,2024-04-13,Wolverhampton Wanderers,Nott'ham Forest,D
650,0,0,2024-04-20,Wolverhampton Wanderers,Arsenal,L
651,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L
652,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W
653,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L

In [48]:
combined['team'].value_counts()

Bournemouth                 17
Brentford                   17
West Ham United             17
Luton Town                  17
Arsenal                     16
Aston Villa                 16
Sheffield United            16
Nottingham Forest           16
Manchester City             16
Liverpool                   16
Fulham                      16
Everton                     16
Crystal Palace              16
Burnley                     16
Brighton and Hove Albion    16
Wolverhampton Wanderers     16
Manchester United           15
Newcastle United            15
Chelsea                     15
Tottenham Hotspur           15
Name: team, dtype: int64

In [49]:
combined['opponent'].value_counts()

West Ham           17
Bournemouth        17
Brentford          17
Luton Town         17
Crystal Palace     16
Nott'ham Forest    16
Fulham             16
Everton            16
Wolves             16
Aston Villa        16
Brighton           16
Manchester City    16
Sheffield Utd      16
Burnley            16
Liverpool          16
Arsenal            16
Chelsea            15
Tottenham          15
Newcastle Utd      15
Manchester Utd     15
Name: opponent, dtype: int64

In [56]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton",
              "Manchester United": "Manchester Utd",
              "Newcastle United": "Newcastle Utd",
              "Nottingham Forest": "Nott'ham Forest",
              "Tottenham Hotspur": "Tottenham",
              "West Ham United": "West Ham",
              "Wolverhampton Wanderers": "Wolves",
              "Sheffield United": "Sheffield Utd"} 
mapping = MissingDict(**map_values)

In [57]:
combined["new_team"] = combined["team"].map(mapping)

In [58]:
merged = combined.merge(combined, left_on = ["date", "new_team"], right_on = ["date", "opponent"])

In [59]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,1,1,2024-01-20,Arsenal,Crystal Palace,W,Arsenal,0,0,Crystal Palace,Arsenal,L,Crystal Palace
1,1,1,2024-01-30,Arsenal,Nott'ham Forest,W,Arsenal,0,0,Nottingham Forest,Arsenal,L,Nott'ham Forest
2,1,1,2024-02-04,Arsenal,Liverpool,W,Arsenal,0,0,Liverpool,Arsenal,L,Liverpool
3,1,0,2024-02-11,Arsenal,West Ham,W,Arsenal,0,0,West Ham United,Arsenal,L,West Ham
4,1,0,2024-02-17,Arsenal,Burnley,W,Arsenal,0,0,Burnley,Arsenal,L,Burnley
...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,0,0,2024-04-13,Wolverhampton Wanderers,Nott'ham Forest,D,Wolves,0,1,Nottingham Forest,Wolves,D,Nott'ham Forest
316,0,0,2024-04-20,Wolverhampton Wanderers,Arsenal,L,Wolves,1,0,Arsenal,Wolves,W,Arsenal
317,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L,Wolves,1,0,Bournemouth,Wolves,W,Bournemouth
318,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W,Wolves,0,0,Luton Town,Wolves,L,Luton Town
319,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L,Wolves,1,1,Manchester City,Wolves,W,Manchester City

In [61]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 0)]["actual_x"].value_counts()

1    50
0    34
Name: actual_x, dtype: int64

In [62]:
merged[(merged["predicted_x"] == 0) & (merged["predicted_y"] == 1)]["actual_x"].value_counts()

0    70
1    14
Name: actual_x, dtype: int64

In [63]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 1)]["actual_x"].value_counts()

0    6
1    4
Name: actual_x, dtype: int64

In [64]:
merged[(merged["predicted_x"] == 0) & (merged["predicted_y"] == 0)]["actual_x"].value_counts()

0    94
1    48
Name: actual_x, dtype: int64

In [65]:
50+34+84+10+94+48

320